<?php
add_filter( 'osf_customize_colors', 'osf_typography_custom_color', 10, 7 );
function osf_typography_custom_color($cssCode, $color_primary, $color_primary_hover, $color_secondary, $color_secondary_hover, $color_body, $color_heading) {
    // require_once trailingslashit(FUNDOR_CORE_PLUGIN_DIR) . 'inc/scssphp-master/scss.inc.php';

    // $phpScss = new ScssPhp\ScssPhp\Compiler();
    $cssCode .= <<<CSS

input[type="text"]::placeholder,
input[type="email"]::placeholder,
input[type="url"]::placeholder,
input[type="password"]::placeholder,
input[type="search"]::placeholder,
input[type="number"]::placeholder,
input[type="tel"]::placeholder,
input[type="range"]::placeholder,
input[type="date"]::placeholder,
input[type="month"]::placeholder,
input[type="week"]::placeholder,
input[type="time"]::placeholder,
input[type="datetime"]::placeholder,
input[type="datetime-local"]::placeholder,
input[type="color"]::placeholder,
input[type="text"],
input[type="email"],
input[type="url"],
input[type="password"],
input[type="search"],
input[type="number"],
input[type="tel"],
input[type="range"],
input[type="date"],
input[type="month"],
input[type="week"],
input[type="time"],
input[type="datetime"],
input[type="datetime-local"],
input[type="color"],
textarea::placeholder,
textarea,
a,
.mainmenu-container li a span,
.post-date a,
.comment-metadata,
.widget_search button[type="submit"],
.c-body,
.site-header-account .account-links-menu li a,
.site-header-account .account-dashboard li a,
.comment-form a,
.elementor-widget-opal-give-campain .give-card__text,
.elementor-nav-menu--dropdown a,
.elementor-search-form--skin-minimal .elementor-search-form__icon,
form[id*='give-form'] .form-row select.required,
form[id*='give-form'] .form-row textarea.required,
form[id*='give-form'] .form-row input.required[type="text"],
form[id*='give-form'] .form-row input.required[type="tel"],
form[id*='give-form'] .form-row input.required[type="email"],
form[id*='give-form'] .form-row input.required[type="password"],
form[id*='give-form'] .form-row input.required[type="url"],
#give-recurring-form .form-row select.required,
#give-recurring-form .form-row textarea.required,
#give-recurring-form .form-row input.required[type="text"],
#give-recurring-form .form-row input.required[type="tel"],
#give-recurring-form .form-row input.required[type="email"],
#give-recurring-form .form-row input.required[type="password"],
#give-recurring-form .form-row input.required[type="url"],
form.give-form .form-row select.required,
form.give-form .form-row textarea.required,
form.give-form .form-row input.required[type="text"],
form.give-form .form-row input.required[type="tel"],
form.give-form .form-row input.required[type="email"],
form.give-form .form-row input.required[type="password"],
form.give-form .form-row input.required[type="url"],
table.give-table {
  color: {$color_body}; }



.widget-area strong,
h1,
h2,
h3,
h4,
h5,
h6,
blockquote a:not(.more-link),
fieldset legend,
th,
.main-navigation .top-menu > li > a,
.site-header .sticky-show .site-description,
.site-header .sticky-show .site-title a,
.site-header .sticky-show .mainmenu-container .top-menu > li > a,
.post-content .posted-on a,
.entry-meta a i,
.entry-content strong,
.entry-content dt,
.entry-content th,
.entry-content dt a,
.entry-content th a,
body.single-post article.type-post .entry-title,
.single-osf_event article.type-post .entry-title,
body.single-post .post-navigation .nav-links .nav-links-inner .nav-title,
.single-osf_event .post-navigation .nav-links .nav-links-inner .nav-title,
.post-related-block > h3,
.comments-title,
.comment-content strong,
.comment-author,
.comment-author a,
.comment-metadata a.comment-edit-link,
.comment-reply-link,
.comment-content table th,
.comment-content table td a,
.comment-content dt,
.comment-respond .comment-reply-title,
.widget a,
.widget.osf_widget_campaign ul li,
.widget.widget_archive ul li,
.widget.widget_categories ul li,
.widget.widget_nav_menu ul li,
.widget.widget_meta ul li,
.widget.widget_pages ul li,
.widget.osf_widget_campaign a,
.widget.widget_archive a,
.widget.widget_categories a,
.widget.widget_nav_menu a,
.widget.widget_meta a,
.widget.widget_pages a,
.widget.media-post-layout .entry-meta i,
.widget_rss .rss-date,
.widget_rss li cite,
.c-heading,
.related-posts .related-heading,
.author-wrapper .author-name,
.page .entry-header .entry-title,
.search .site-content .page-title,
.site-header-account .login-form-title,
.elementor-widget-accordion .elementor-accordion .elementor-tab-title,
.elementor-counter .elementor-counter-number-wrapper,
.elementor-widget-icon-box:not(:hover) .elementor-icon-box-title,
.elementor-teams-wrapper .elementor-team-name,
form[id*='give-form'] .give-donation-amount #give-amount,
form[id*='give-form'] .give-donation-amount #give-amount-text,
.opal-give-message p,
#give-email-access-form label,
#give-login-form label,
#give-login-form legend,
.give-goal-progress .percentage,
.give-wrap .give-card__meta a {
  color: {$color_heading}; }




.btn-link,
.elementor-element .elementor-button-link .elementor-button,
.button-link,
.mailchimp-button-link button,
.mailchimp-button-link button[type="submit"],
.breadcrumb,
.breadcrumb .separator,
.mainmenu-container li.current-menu-parent > a,
.mainmenu-container .menu-item > a:hover,
.mainmenu-container li li.current_page_item a:hover,
.mainmenu-container li li.current-menu-item a:hover,
.mainmenu-container li li.current_page_item a:focus,
.mainmenu-container li li.current-menu-item a:focus,
.site-header .mainmenu-container .top-menu > li.current-menu-item > a,
.site-header .mainmenu-container .top-menu > li:hover > a,
.page-numbers.next:hover,
.page-links .next.post-page-numbers:hover,
.page-numbers.prev:hover,
.page-links .prev.post-page-numbers:hover,
.site-header .header-group .search-submit:hover,
.site-header .header-group .search-submit:focus,
.post-content .posted-on a:hover,
.entry-title a:hover,
.entry-meta .entry-category,
.entry-meta .entry-category a,
.pbr-social-share a:hover,
body.single-post .post-navigation .nav-links .nav-links-inner .meta-nav,
.single-osf_event .post-navigation .nav-links .nav-links-inner .meta-nav,
.wp-block-calendar tfoot a:hover,
.error404 h1,
.site-footer .widget.widget_archive a:hover,
.site-footer .widget.widget_archive a:focus,
.site-footer .widget.widget_categories a:hover,
.site-footer .widget.widget_categories a:focus,
.site-footer .widget.widget_nav_menu a:hover,
.site-footer .widget.widget_nav_menu a:focus,
.site-footer .widget.widget_meta a:hover,
.site-footer .widget.widget_meta a:focus,
.site-footer .widget.widget_pages a:hover,
.site-footer .widget.widget_pages a:focus,
.site-footer .widget a:hover,
.site-footer .widget a:focus,
.site-info a,
.breadcrumb a:hover,
.breadcrumb a:hover span,
.comment-author a:hover,
.comment-metadata a:hover,
.widget a:hover,
.widget a:focus,
.widget.osf_widget_campaign a:hover,
.widget.osf_widget_campaign a:focus,
.widget.widget_archive a:hover,
.widget.widget_archive a:focus,
.widget.widget_categories a:hover,
.widget.widget_categories a:focus,
.widget.widget_nav_menu a:hover,
.widget.widget_nav_menu a:focus,
.widget.widget_meta a:hover,
.widget.widget_meta a:focus,
.widget.widget_pages a:hover,
.widget.widget_pages a:focus,
h2.widget-title,
h2.widgettitle,
.profile-wrapper .login-form-title,
.widget_recent_entries li a:hover,
.widget_recent_entries li a:active,
.button-outline-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.post-inner .more-link,
.more-link,
.comment-form .form-submit input[type="submit"],
.elementor-wpcf7-button-outline_primary input[type="button"],
.elementor-wpcf7-button-outline_primary input[type="submit"],
.elementor-wpcf7-button-outline_primary button[type="submit"],
.mailchimp-button-outline_primary button,
.mailchimp-button-outline_primary button[type="submit"],
.elementor-element .elementor-button-outline_primary .elementor-button,
.c-primary,
.navigation-button .menu-toggle:hover,
.navigation-button .menu-toggle:focus,
.site-header-account .account-dropdown a.register-link,
.site-header-account .account-dropdown a.lostpass-link,
.site-header-account .account-links-menu li a:hover,
.site-header-account .account-dashboard li a:hover,
.comment-form a:hover,
.wp_widget_tag_cloud a:hover,
.wp_widget_tag_cloud a:focus,
#secondary .elementor-widget-container h5:first-of-type,
.elementor-widget-sidebar .elementor-widget-container h5:first-of-type,
#give-sidebar-left .elementor-widget-container h5:first-of-type,
.elementor-nav-menu-popup .mfp-close,
#secondary .elementor-widget-wp-widget-recent-posts a,
.elementor-widget-sidebar .elementor-widget-wp-widget-recent-posts a,
#give-sidebar-left .elementor-widget-wp-widget-recent-posts a,
.elementor-widget-accordion .elementor-accordion .elementor-tab-title .elementor-accordion-icon,
.contactform-content .form-title,
.elementor-widget-opal-countdown .elementor-countdown-digits,
.dual-heading-container .dual-heading-second-header,
.elementor-widget-opal-featured-box .elementor-featured-box-name:hover,
.feature-campaign__item .campaign-body .campaign-head .give-card__title a:hover,
.campain-grid-style-2 .give-wrap .give-goal-progress .raised .percentage,
.elementor-widget-heading .sub-title,
.elementor-widget-icon-box:not(:hover) .elementor-icon,
.elementor-widget-icon-box:hover .elementor-icon,
.elementor-widget-icon-box:hover .elementor-icon-box-title,
.elementor-widget-opal-image-hotspots .elementor-hotspots-item-number,
.elementor-widget-opal-image-gallery .elementor-galerry__filter.elementor-active,
.elementor-widget-opal-image-gallery .elementor-galerry__filter.elementor-active sup,
.elementor-widget-item-list .elementor-item-list-number,
.mailchimp-button-default button i,
.mailchimp-button-default button[type="submit"] i,
.mailchimp-button-default button:hover,
.mailchimp-button-default button[type="submit"]:hover,
.elementor-nav-menu--main.elementor-nav-menu--layout-horizontal .elementor-nav-menu a.elementor-sub-item.elementor-item-active,
.elementor-nav-menu--main .elementor-item.highlighted,
.elementor-nav-menu--main .elementor-item.elementor-item-active,
.elementor-nav-menu--main .elementor-item:hover,
.elementor-nav-menu--main .elementor-item:focus,
.elementor-nav-menu--main .current-menu-ancestor .elementor-item.has-submenu,
.elementor-nav-menu--main .current-menu-item .elementor-item,
.elementor-nav-menu--popup .elementor-item.highlighted,
.elementor-nav-menu--popup .elementor-item.elementor-item-active,
.elementor-nav-menu--popup .elementor-item:hover,
.elementor-nav-menu--popup .elementor-item:focus,
.elementor-nav-menu--popup .elementor-nav-menu--dropdown a:hover,
.elementor-nav-menu--popup .elementor-nav-menu--dropdown a.highlighted,
.elementor-nav-menu--dropdown:not(.mega-menu) a:hover,
.elementor-nav-menu--dropdown:not(.mega-menu) a.highlighted,
.elementor-nav-menu--dropdown:not(.mega-menu) a.has-submenu,
.elementor-menu-toggle:hover i,
.elementor-menu-toggle:hover .menu-toggle-title,
.elementor-widget-opal-phone:not(:hover) i,
.elementor-widget-opal-phone:not(:hover) .elementor-phone-title,
.elementor-widget-opal-phone:not(:hover) .elementor-phone-subtitle,
.elementor-widget-opal-popup-template .elementor-toggle i:hover,
.elementor-widget-opal-popup-template .button-close:hover,
.elementor-price-table__ribbon,
.elementor-widget-opal-reason_carousel .elementor-content-wrap:hover .elementor-heading-title,
.elementor-widget-opal-schedules .schedules-item:hover .title-schedules,
.elementor-widget-opal-schedules .item-meta i,
.elementor-widget-opal-schedules .author-schedules a:hover,
.elementor-widget-opal-schedules .button-schedules:hover i,
.elementor-widget-opal-schedules .button-schedules.active i,
.elementor-search-form .elementor-search-form__submit:hover,
.elementor-search-form--skin-full_screen .elementor-search-form__toggle:hover,
.elementor-widget-social-icons.elementor-social-custom .elementor-social-icon:hover i,
.elementor-widget-opal-story-grid .post-inner .more-link:hover,
.elementor-widget-opal-story-grid .entry-meta a:hover,
.elementor-widget-opal-tabs.elementor-widget-tabs .elementor-tab-desktop-title:hover,
.elementor-widget-opal-tabs.elementor-widget-tabs .elementor-tab-desktop-title.elementor-active,
.elementor-teams-wrapper .elementor-team-job,
.elementor-teams-wrapper .team-icon-socials a:hover,
.elementor-video-popup:hover .elementor-video-icons,
.elementor-video-popup:hover .elementor-video-title,
form[id*='give-form'] #give-final-total-wrap .give-final-total-amount,
#give_profile_editor_form legend i,
.img-give-form i,
#give-login-form legend:after,
.sidebar-donor-wall .give-donor__read-more:hover,
.archive-give-forms .give-wrap .give-goal-progress .raised .percentage,
table.give-table a,
.give-donor__total,
.profile-wrapper .login-profile .lostpass-link,
.profile-wrapper .login-profile .register-link,
.profile-campaign__item .campaign-meta a:hover,
.profile-campaign__item .give-card__title a:hover,
.give-wrap .give-card__meta a:hover,
.give-wrap .give-card__category,
.give-wrap .give-form-tabs .ui-tabs-nav li sup,
.give-wrap .give-form-tabs .ui-tabs-nav li:hover a,
.give-wrap .give-form-tabs .ui-tabs-nav li a:focus,
.give-wrap .give-form-tabs .ui-tabs-nav li.ui-tabs-active a,
.give-wrap .sidebar-creator .campaigns-count,
.single-osf_story .post-navigation .nav-links .nav-links-inner:hover .nav-title,
.single-osf_story .post-navigation .nav-links .nav-links-inner:hover a .nav-title,
.post-type-archive-osf_story .entry-meta a:hover,
.tax-osf_story_category .entry-meta a:hover,
.post-type-archive-osf_story .more-link:hover,
.tax-osf_story_category .more-link:hover {
  color: {$color_primary->toCss()}; }


.f-primary {
  fill: {$color_primary->toCss()}; }


.button-default:hover,
.sidebar-donor-wall .give-donor__load_more:hover,
.button-primary-gradient,
::selection,
.mainmenu-container ul ul .menu-item > a:hover,
.mainmenu-container ul ul .menu-item > a:active,
.mainmenu-container ul ul .menu-item > a:focus,
.page-numbers:not(.dots):not(.next):not(.prev):hover,
.page-links .post-page-numbers:not(.dots):not(.next):not(.prev):hover,
.page-numbers:not(.dots):not(.next):not(.prev):focus,
.page-links .post-page-numbers:not(.dots):not(.next):not(.prev):focus,
.page-numbers.current:not(.dots):not(.next):not(.prev),
.page-links .current.post-page-numbers:not(.dots):not(.next):not(.prev),
.comments-link span,
.post-content .posted-on:after,
.cat-tags-links .tags-links a:hover,
body.single-post .post-navigation .nav-links .nav-links-inner:hover,
.single-osf_event .post-navigation .nav-links .nav-links-inner:hover,
.post-related-block .swiper-pagination-bullet,
.wp-block-tag-cloud a:hover,
.site-footer .widget .tagcloud a:hover,
.site-footer .widget .tagcloud a:focus,
.site-footer .widget.widget_tag_cloud a:hover,
.site-footer .widget.widget_tag_cloud a:focus,
.widget.osf_widget_campaign a:before,
.widget.widget_archive a:before,
.widget.widget_categories a:before,
.widget.widget_nav_menu a:before,
.widget.widget_meta a:before,
.widget.widget_pages a:before,
h2.widget-title:before,
h2.widgettitle:before,
.profile-wrapper .login-form-title:before,
.widget .tagcloud a:hover,
.widget .tagcloud a:focus,
.widget.widget_tag_cloud a:hover,
.widget.widget_tag_cloud a:focus,
.button-primary,
.scrollup,
.elementor-widget-opal-account .site-header-account .account-dropdown .account-inner button[type="submit"],
.contactform-content input[type="button"],
.contactform-content input[type="submit"],
.contactform-content button[type="submit"],
.elementor-wpcf7-button-primary_gradient input[type="button"][type="submit"],
.elementor-wpcf7-button-primary_gradient input[type="submit"],
.elementor-wpcf7-button-primary_gradient button[type="submit"],
.elementor-wpcf7-button-primary input[type="button"][type="submit"],
.elementor-wpcf7-button-primary input[type="submit"],
.elementor-wpcf7-button-primary button[type="submit"],
.elementor-widget-opal-give-form .give-submit-button-wrap .give-submit,
.mailchimp-button-primary button,
.mailchimp-button-primary button[type="submit"],
[id^='give-user-login-submit'] .give-submit,
.give-submit-button-wrap .give-submit,
button.give-btn-reveal,
button.give-btn-modal,
.give-wrap .btn-donate-now,
.button-dark:hover,
.elementor-element .elementor-button-dark .elementor-button:hover,
.mailchimp-button-dark button:hover,
.button-dark:active,
.elementor-element .elementor-button-dark .elementor-button:active,
.mailchimp-button-dark button:active,
.button-dark:focus,
.elementor-element .elementor-button-dark .elementor-button:focus,
.mailchimp-button-dark button:focus,
.button-light:hover,
.elementor-element .elementor-button-light .elementor-button:hover,
.mailchimp-button-light button:hover,
.button-light:active,
.elementor-element .elementor-button-light .elementor-button:active,
.mailchimp-button-light button:active,
.button-light:focus,
.elementor-element .elementor-button-light .elementor-button:focus,
.mailchimp-button-light button:focus,
.wp-block-button__link:hover,
.elementor-element .elementor-button-primary .elementor-button,
.button-outline-primary:hover,
input:hover[type="reset"],
input:hover[type="button"],
input:hover[type="submit"],
button:hover[type="submit"],
.more-link:hover,
.comment-form .form-submit input:hover[type="submit"],
.mailchimp-button-outline_primary button:hover,
.button-outline-primary:active,
input:active[type="reset"],
input:active[type="button"],
input:active[type="submit"],
button:active[type="submit"],
.more-link:active,
.comment-form .form-submit input:active[type="submit"],
.mailchimp-button-outline_primary button:active,
.button-outline-primary.active,
input.active[type="reset"],
input.active[type="button"],
input.active[type="submit"],
button.active[type="submit"],
.active.more-link,
.comment-form .form-submit input.active[type="submit"],
.mailchimp-button-outline_primary button.active,
.show > .button-outline-primary.dropdown-toggle,
.show > input.dropdown-toggle[type="reset"],
.show > input.dropdown-toggle[type="button"],
.show > input.dropdown-toggle[type="submit"],
.show > button.dropdown-toggle[type="submit"],
.post-inner .show > .dropdown-toggle.more-link,
.show > .dropdown-toggle.more-link,
.comment-form .form-submit .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-outline_primary .show > input.dropdown-toggle[type="button"],
.elementor-wpcf7-button-outline_primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-outline_primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-outline_primary .show > button.dropdown-toggle,
.post-inner .more-link.active,
.show > .post-inner .more-link.dropdown-toggle,
.elementor-element .elementor-button-outline_primary .elementor-button:hover,
.elementor-element .elementor-button-outline_primary .elementor-button:active,
.elementor-element .elementor-button-outline_primary .elementor-button:focus,
.bg-primary,
.owl-theme.owl-carousel .owl-dots .owl-dot:hover span,
.owl-theme.owl-carousel .owl-dots .owl-dot.active span,
.elementor-widget-opal-account .site-header-account .account-dashboard li a:hover,
.img-animated .elementor-image:after,
.col-animated:after,
.elementor-element .elementor-button:hover,
.elementor-element .elementor-button:active,
.elementor-element .elementor-button:focus,
.contactform-content:before,
.call-to-action-decor-fa .call-to-action-decor,
.elementor-show-before-yes .wpcf7:before,
.elementor-counter .heading-decor,
.elementor-widget-divider .elementor-divider-separator:before,
.elementor-flip-box__front,
.categories_bkg,
.categories_bkg:before,
.categories_bkg:after,
.elementor-widget-opal-give-form .give-display-onpage form[id*='give-form'] .give-donation-amount .give-currency-position-before,
.elementor-widget-heading .heading-decor,
.elementor-widget-icon-box .image-box-decor,
.elementor-widget-image-box .image-box-decor,
.opal-image-hotspots-main-icons .opal-image-hotspots-icon:not(.style-2):after,
.opal-image-hotspots-main-icons .opal-image-hotspots-icon.style-2:hover,
.tooltipster-sidetip div.tooltipster-box,
.elementor-widget-opal-image-gallery .elementor-galerry__filter:before,
.elementor-nav-menu--main.elementor-nav-menu--layout-horizontal:not(.e--pointer-framed) .elementor-nav-menu > li.current-menu-parent > a:before,
.elementor-nav-menu--main.elementor-nav-menu--layout-horizontal:not(.e--pointer-framed) .elementor-nav-menu > li.current-menu-parent > a:after,
.elementor-nav-menu--main.e--pointer-dot .elementor-item.elementor-item-active:before,
.elementor-nav-menu--main.e--pointer-dot .elementor-item:not(:hover):before,
.elementor-nav-menu--main.e--pointer-dot .elementor-item:hover:before,
.elementor-nav-menu--main:not(.e--pointer-framed) .elementor-item.elementor-item-active:before,
.elementor-nav-menu--main:not(.e--pointer-framed) .elementor-item.elementor-item-active:after,
.elementor-nav-menu--main:not(.e--pointer-framed) .elementor-item:before,
.elementor-nav-menu--main:not(.e--pointer-framed) .elementor-item:after,
.elementor-nav-menu--popup.e--pointer-dot .elementor-item.elementor-item-active:before,
.elementor-nav-menu--popup.e--pointer-dot .elementor-item:hover:before,
.e--pointer-dot .elementor-item:before,
.e--pointer-underline .elementor-item .menu-title:before,
.e--pointer-underline .elementor-item .menu-title:after,
.elementor-price-table,
.elementor-widget-opal-reason_carousel .elementor-reason-number span,
.elementor-widget-opal-schedules .item-icon_label .icon-label,
.elementor-widget-opal-schedules .schedules-style-1 .schedules-day:before,
.elementor-widget-opal-schedules .schedules-style-2 .schedules-day,
.elementor-widget-opal-schedules .schedules-style-3 .schedules-day:before,
.elementor-widget-opal-tabs.elementor-widget-tabs.elementor-widget-tabs.elementor-tabs-view-vertical .elementor-tab-title.elementor-active span:after,
.elementor-widget-opal-text_carousel.text-carousel-style-2 .owl-theme.owl-carousel .owl-nav [class*='owl-']:hover:before,
[id*='give-form'] div#give-sidebar-left .give-goal-progress .button-progress-link:hover,
form[id*='give-form'] input[type="radio"]:checked + label:after,
.give-progress-bar > span,
.give-progress-bar > span:after,
.profile-wrapper .account-title:after,
.profile-campaign__item .edit-campaign:hover,
.profile-campaign__item .delete-campaign:hover,
.author-profile-campaign-title:before,
.give-wrap .give-card__body .wrap-label .label.success,
.give-wrap .opal-popup-wrapper [class*="opal-icon-"]:hover,
.give-wrap .give-form-tabs .ui-tabs-nav a:after {
  background-color: {$color_primary->toCss()}; }



.button-primary,
.scrollup,
.elementor-widget-opal-account .site-header-account .account-dropdown .account-inner button[type="submit"],
.contactform-content input[type="button"],
.contactform-content input[type="submit"],
.contactform-content button[type="submit"],
.elementor-wpcf7-button-primary_gradient input[type="button"][type="submit"],
.elementor-wpcf7-button-primary_gradient input[type="submit"],
.elementor-wpcf7-button-primary_gradient button[type="submit"],
.elementor-wpcf7-button-primary input[type="button"][type="submit"],
.elementor-wpcf7-button-primary input[type="submit"],
.elementor-wpcf7-button-primary button[type="submit"],
.elementor-widget-opal-give-form .give-submit-button-wrap .give-submit,
.mailchimp-button-primary button,
.mailchimp-button-primary button[type="submit"],
[id^='give-user-login-submit'] .give-submit,
.give-submit-button-wrap .give-submit,
button.give-btn-reveal,
button.give-btn-modal,
.give-wrap .btn-donate-now,
.button-secondary,
.secondary-button .search-submit,
.elementor-wpcf7-button-secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-secondary input[type="submit"],
.elementor-wpcf7-button-secondary button[type="submit"],
.mailchimp-button-secondary button,
.mailchimp-button-secondary button[type="submit"],
.button-default:hover,
.sidebar-donor-wall .give-donor__load_more:hover,
.form-control:focus,
input[type="text"]:focus,
input[type="email"]:focus,
input[type="url"]:focus,
input[type="password"]:focus,
input[type="search"]:focus,
input[type="number"]:focus,
input[type="tel"]:focus,
input[type="range"]:focus,
input[type="date"]:focus,
input[type="month"]:focus,
input[type="week"]:focus,
input[type="time"]:focus,
input[type="datetime"]:focus,
input[type="datetime-local"]:focus,
input[type="color"]:focus,
textarea:focus,
.page-numbers:not(.dots):not(.next):not(.prev):hover,
.page-links .post-page-numbers:not(.dots):not(.next):not(.prev):hover,
.page-numbers:not(.dots):not(.next):not(.prev):focus,
.page-links .post-page-numbers:not(.dots):not(.next):not(.prev):focus,
.page-numbers.current:not(.dots):not(.next):not(.prev),
.page-links .current.post-page-numbers:not(.dots):not(.next):not(.prev),
.button-dark:hover,
.elementor-element .elementor-button-dark .elementor-button:hover,
.mailchimp-button-dark button:hover,
.button-dark:active,
.elementor-element .elementor-button-dark .elementor-button:active,
.mailchimp-button-dark button:active,
.button-dark:focus,
.elementor-element .elementor-button-dark .elementor-button:focus,
.mailchimp-button-dark button:focus,
.button-light:hover,
.elementor-element .elementor-button-light .elementor-button:hover,
.mailchimp-button-light button:hover,
.button-light:active,
.elementor-element .elementor-button-light .elementor-button:active,
.mailchimp-button-light button:active,
.button-light:focus,
.elementor-element .elementor-button-light .elementor-button:focus,
.mailchimp-button-light button:focus,
.wp-block-button__link:hover,
.elementor-element .elementor-button-primary .elementor-button,
.button-outline-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.post-inner .more-link,
.more-link,
.comment-form .form-submit input[type="submit"],
.elementor-wpcf7-button-outline_primary input[type="button"],
.elementor-wpcf7-button-outline_primary input[type="submit"],
.elementor-wpcf7-button-outline_primary button[type="submit"],
.mailchimp-button-outline_primary button,
.mailchimp-button-outline_primary button[type="submit"],
.elementor-element .elementor-button-outline_primary .elementor-button,
.button-outline-primary:hover,
input:hover[type="reset"],
input:hover[type="button"],
input:hover[type="submit"],
button:hover[type="submit"],
.more-link:hover,
.comment-form .form-submit input:hover[type="submit"],
.mailchimp-button-outline_primary button:hover,
.button-outline-primary:active,
input:active[type="reset"],
input:active[type="button"],
input:active[type="submit"],
button:active[type="submit"],
.more-link:active,
.comment-form .form-submit input:active[type="submit"],
.mailchimp-button-outline_primary button:active,
.button-outline-primary.active,
input.active[type="reset"],
input.active[type="button"],
input.active[type="submit"],
button.active[type="submit"],
.active.more-link,
.comment-form .form-submit input.active[type="submit"],
.mailchimp-button-outline_primary button.active,
.show > .button-outline-primary.dropdown-toggle,
.show > input.dropdown-toggle[type="reset"],
.show > input.dropdown-toggle[type="button"],
.show > input.dropdown-toggle[type="submit"],
.show > button.dropdown-toggle[type="submit"],
.post-inner .show > .dropdown-toggle.more-link,
.show > .dropdown-toggle.more-link,
.comment-form .form-submit .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-outline_primary .show > input.dropdown-toggle[type="button"],
.elementor-wpcf7-button-outline_primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-outline_primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-outline_primary .show > button.dropdown-toggle,
.post-inner .more-link.active,
.show > .post-inner .more-link.dropdown-toggle,
.elementor-element .elementor-button-outline_primary .elementor-button:hover,
.elementor-element .elementor-button-outline_primary .elementor-button:active,
.elementor-element .elementor-button-outline_primary .elementor-button:focus,
.b-primary,
.elementor-widget-opal-give-form .give-display-onpage form[id*='give-form'] .give-donation-amount #give-amount:hover,
.elementor-widget-opal-give-form .give-display-onpage form[id*='give-form'] .give-donation-amount #give-amount:focus,
.elementor-widget-opal-give-form .give-display-onpage form[id*='give-form'] .give-donation-amount #give-text-input:hover,
.elementor-widget-opal-give-form .give-display-onpage form[id*='give-form'] .give-donation-amount #give-text-input:focus,
.elementor-widget-opal-give-form .give-display-onpage form[id*='give-form'] .give-donation-amount #give-amount-text:hover,
.elementor-widget-opal-give-form .give-display-onpage form[id*='give-form'] .give-donation-amount #give-amount-text:focus,
.elementor-widget-icon-box:hover .elementor-icon,
.elementor-widget-icon-box:hover .elementor-icon-box-title,
.opal-image-hotspots-main-icons .opal-image-hotspots-icon:not(.style-2):before,
.mc4wp-form-fields:focus-within,
.e--pointer-framed .elementor-item.elementor-item-active:before,
.e--pointer-framed .elementor-item.elementor-item-active:after,
.e--pointer-framed .elementor-item:before,
.e--pointer-framed .elementor-item:after,
.elementor-nav-menu--main > .elementor-nav-menu,
.elementor-nav-menu--main .elementor-nav-menu ul,
.elementor-widget-opal-post-grid .post-news,
.elementor-search-form--skin-full_screen .elementor-search-form__toggle:hover,
.elementor-widget-opal-text_carousel.text-carousel-style-2 .elementor-content-wrap,
.elementor-video-popup:hover .elementor-video-icons,
.elementor-video-popup:hover .elementor-video-title,
[id*='give-form'] div#give-sidebar-left .give-goal-progress .button-progress-link:hover,
form[id*='give-form'] .form-row select:focus,
form[id*='give-form'] .form-row textarea:focus,
form[id*='give-form'] .form-row input[type="text"]:focus,
form[id*='give-form'] .form-row input[type="tel"]:focus,
form[id*='give-form'] .form-row input[type="email"]:focus,
form[id*='give-form'] .form-row input[type="password"]:focus,
form[id*='give-form'] .form-row input[type="url"]:focus,
#give-recurring-form .form-row select:focus,
#give-recurring-form .form-row textarea:focus,
#give-recurring-form .form-row input[type="text"]:focus,
#give-recurring-form .form-row input[type="tel"]:focus,
#give-recurring-form .form-row input[type="email"]:focus,
#give-recurring-form .form-row input[type="password"]:focus,
#give-recurring-form .form-row input[type="url"]:focus,
form.give-form .form-row select:focus,
form.give-form .form-row textarea:focus,
form.give-form .form-row input[type="text"]:focus,
form.give-form .form-row input[type="tel"]:focus,
form.give-form .form-row input[type="email"]:focus,
form.give-form .form-row input[type="password"]:focus,
form.give-form .form-row input[type="url"]:focus {
  border-color: {$color_primary->toCss()}; }


.tooltipster-base.tooltipster-top .tooltipster-arrow-background,
.elementor-widget-opal-reason_carousel .elementor-content-wrap,
.elementor-widget-opal-tabs.elementor-widget-tabs.elementor-widget-tabs.elementor-tabs-view-horizontal .elementor-tab-title.elementor-active,
.elementor-widget-opal-tabs.elementor-widget-tabs.elementor-widget-tabs.elementor-tabs-view-horizontal .elementor-tab-title:hover {
  border-top-color: {$color_primary->toCss()}; }


.tooltipster-base.tooltipster-bottom .tooltipster-arrow-background,
.elementor-nav-menu--layout-horizontal .elementor-nav-menu li.menu-item-has-children:before,
.elementor-nav-menu--layout-horizontal .elementor-nav-menu li.has-mega-menu:before,
.elementor-widget-opal-tabs.elementor-widget-tabs.elementor-widget-tabs.elementor-tabs-view-horizontal .elementor-tab-title.elementor-active,
.elementor-widget-opal-tabs.elementor-widget-tabs.elementor-widget-tabs.elementor-tabs-view-horizontal .elementor-tab-title:hover,
.profile-sidebar-inner .profile-sidebar-link a.active,
.profile-sidebar-inner .profile-sidebar-link li.active a {
  border-bottom-color: {$color_primary->toCss()}; }


.tooltipster-base.tooltipster-left .tooltipster-arrow-background {
  border-left-color: {$color_primary->toCss()}; }


.tooltipster-base.tooltipster-right .tooltipster-arrow-background {
  border-right-color: {$color_primary->toCss()}; }



.btn-link:focus,
.elementor-element .elementor-button-link .elementor-button:focus,
.btn-link:hover,
.elementor-element .elementor-button-link .elementor-button:hover,
.button-link:focus,
.mailchimp-button-link button:focus,
.button-link:hover,
.mailchimp-button-link button:hover,
a:hover,
a:active,
.widget_search button[type="submit"]:hover,
.widget_search button[type="submit"]:focus,
.elementor-widget-opal-phone:hover i,
.elementor-widget-opal-phone:hover .elementor-phone-title,
.elementor-widget-opal-phone:hover .elementor-phone-subtitle,
.profile-wrapper .login-profile .lostpass-link:hover,
.profile-wrapper .login-profile .register-link:hover,
.profile-wrapper .profile-avatar .opal-give-button-edit-avatar:hover {
  color: {$color_primary_hover->toCss()}; }


.button-primary:hover,
.scrollup:hover,
.elementor-widget-opal-account .site-header-account .account-dropdown .account-inner button:hover[type="submit"],
.contactform-content input:hover[type="button"],
.contactform-content input:hover[type="submit"],
.contactform-content button:hover[type="submit"],
.elementor-wpcf7-button-primary_gradient input:hover[type="submit"],
.elementor-wpcf7-button-primary_gradient button:hover[type="submit"],
.elementor-wpcf7-button-primary input:hover[type="submit"],
.elementor-wpcf7-button-primary button:hover[type="submit"],
.mailchimp-button-primary button:hover,
[id^='give-user-login-submit'] .give-submit:hover,
.give-submit-button-wrap .give-submit:hover,
button.give-btn-reveal:hover,
button.give-btn-modal:hover,
.give-wrap .btn-donate-now:hover,
.button-primary:active,
.scrollup:active,
.elementor-widget-opal-account .site-header-account .account-dropdown .account-inner button:active[type="submit"],
.contactform-content input:active[type="button"],
.contactform-content input:active[type="submit"],
.contactform-content button:active[type="submit"],
.elementor-wpcf7-button-primary_gradient input:active[type="submit"],
.elementor-wpcf7-button-primary_gradient button:active[type="submit"],
.elementor-wpcf7-button-primary input:active[type="submit"],
.elementor-wpcf7-button-primary button:active[type="submit"],
.mailchimp-button-primary button:active,
[id^='give-user-login-submit'] .give-submit:active,
.give-submit-button-wrap .give-submit:active,
button.give-btn-reveal:active,
button.give-btn-modal:active,
.give-wrap .btn-donate-now:active,
.button-primary.active,
.active.scrollup,
.elementor-widget-opal-account .site-header-account .account-dropdown .account-inner button.active[type="submit"],
.contactform-content input.active[type="button"],
.contactform-content input.active[type="submit"],
.contactform-content button.active[type="submit"],
.elementor-wpcf7-button-primary_gradient input.active[type="submit"],
.elementor-wpcf7-button-primary_gradient button.active[type="submit"],
.elementor-wpcf7-button-primary input.active[type="submit"],
.elementor-wpcf7-button-primary button.active[type="submit"],
.mailchimp-button-primary button.active,
[id^='give-user-login-submit'] .active.give-submit,
.give-submit-button-wrap .active.give-submit,
button.active.give-btn-reveal,
button.active.give-btn-modal,
.give-wrap .active.btn-donate-now,
.show > .button-primary.dropdown-toggle,
.show > .dropdown-toggle.scrollup,
.elementor-widget-opal-account .site-header-account .account-dropdown .account-inner .show > button.dropdown-toggle[type="submit"],
.contactform-content .show > input.dropdown-toggle[type="button"],
.contactform-content .show > input.dropdown-toggle[type="submit"],
.contactform-content .show > button.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary_gradient .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary_gradient .show > button.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-primary .show > button.dropdown-toggle,
[id^='give-user-login-submit'] .show > .dropdown-toggle.give-submit,
.give-submit-button-wrap .show > .dropdown-toggle.give-submit,
.show > button.dropdown-toggle.give-btn-reveal,
.show > button.dropdown-toggle.give-btn-modal,
.give-wrap .show > .dropdown-toggle.btn-donate-now,
.elementor-element .elementor-button-primary .elementor-button:hover,
.elementor-element .elementor-button-primary .elementor-button:active,
.elementor-element .elementor-button-primary .elementor-button:focus {
  background-color: {$color_primary_hover->toCss()}; }


.button-primary:active,
.scrollup:active,
.elementor-widget-opal-account .site-header-account .account-dropdown .account-inner button:active[type="submit"],
.contactform-content input:active[type="button"],
.contactform-content input:active[type="submit"],
.contactform-content button:active[type="submit"],
.elementor-wpcf7-button-primary_gradient input:active[type="submit"],
.elementor-wpcf7-button-primary_gradient button:active[type="submit"],
.elementor-wpcf7-button-primary input:active[type="submit"],
.elementor-wpcf7-button-primary button:active[type="submit"],
.mailchimp-button-primary button:active,
[id^='give-user-login-submit'] .give-submit:active,
.give-submit-button-wrap .give-submit:active,
button.give-btn-reveal:active,
button.give-btn-modal:active,
.give-wrap .btn-donate-now:active,
.button-primary.active,
.active.scrollup,
.elementor-widget-opal-account .site-header-account .account-dropdown .account-inner button.active[type="submit"],
.contactform-content input.active[type="button"],
.contactform-content input.active[type="submit"],
.contactform-content button.active[type="submit"],
.elementor-wpcf7-button-primary_gradient input.active[type="submit"],
.elementor-wpcf7-button-primary_gradient button.active[type="submit"],
.elementor-wpcf7-button-primary input.active[type="submit"],
.elementor-wpcf7-button-primary button.active[type="submit"],
.mailchimp-button-primary button.active,
[id^='give-user-login-submit'] .active.give-submit,
.give-submit-button-wrap .active.give-submit,
button.active.give-btn-reveal,
button.active.give-btn-modal,
.give-wrap .active.btn-donate-now,
.show > .button-primary.dropdown-toggle,
.show > .dropdown-toggle.scrollup,
.elementor-widget-opal-account .site-header-account .account-dropdown .account-inner .show > button.dropdown-toggle[type="submit"],
.contactform-content .show > input.dropdown-toggle[type="button"],
.contactform-content .show > input.dropdown-toggle[type="submit"],
.contactform-content .show > button.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary_gradient .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary_gradient .show > button.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-primary .show > button.dropdown-toggle,
[id^='give-user-login-submit'] .show > .dropdown-toggle.give-submit,
.give-submit-button-wrap .show > .dropdown-toggle.give-submit,
.show > button.dropdown-toggle.give-btn-reveal,
.show > button.dropdown-toggle.give-btn-modal,
.give-wrap .show > .dropdown-toggle.btn-donate-now,
.button-secondary:active,
.secondary-button .search-submit:active,
.elementor-wpcf7-button-secondary input:active[type="submit"],
.elementor-wpcf7-button-secondary button:active[type="submit"],
.mailchimp-button-secondary button:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.elementor-wpcf7-button-secondary input.active[type="submit"],
.elementor-wpcf7-button-secondary button.active[type="submit"],
.mailchimp-button-secondary button.active,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit,
.elementor-wpcf7-button-secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-secondary .show > button.dropdown-toggle,
.button-primary:hover,
.scrollup:hover,
.elementor-widget-opal-account .site-header-account .account-dropdown .account-inner button:hover[type="submit"],
.contactform-content input:hover[type="button"],
.contactform-content input:hover[type="submit"],
.contactform-content button:hover[type="submit"],
.elementor-wpcf7-button-primary_gradient input:hover[type="submit"],
.elementor-wpcf7-button-primary_gradient button:hover[type="submit"],
.elementor-wpcf7-button-primary input:hover[type="submit"],
.elementor-wpcf7-button-primary button:hover[type="submit"],
.mailchimp-button-primary button:hover,
[id^='give-user-login-submit'] .give-submit:hover,
.give-submit-button-wrap .give-submit:hover,
button.give-btn-reveal:hover,
button.give-btn-modal:hover,
.give-wrap .btn-donate-now:hover,
.elementor-element .elementor-button-primary .elementor-button:hover,
.elementor-element .elementor-button-primary .elementor-button:active,
.elementor-element .elementor-button-primary .elementor-button:focus {
  border-color: {$color_primary_hover->toCss()}; }




.button-outline-secondary,
.elementor-wpcf7-button-outline_secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-outline_secondary input[type="submit"],
.elementor-wpcf7-button-outline_secondary button[type="submit"],
.mailchimp-button-outline_secondary button,
.mailchimp-button-outline_secondary button[type="submit"],
.elementor-element .elementor-button-outline_secondary .elementor-button,
.c-secondary,
.author-wrapper .author-name h6,
.contactform-content button.mfp-close {
  color: {$color_secondary->toCss()}; }


.f-secondary {
  fill: {$color_secondary->toCss()}; }


blockquote,
.page-links a:hover,
.page-links .post-page-numbers.current,
.button-secondary,
.secondary-button .search-submit,
.elementor-wpcf7-button-secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-secondary input[type="submit"],
.elementor-wpcf7-button-secondary button[type="submit"],
.mailchimp-button-secondary button,
.mailchimp-button-secondary button[type="submit"],
.elementor-button-secondary button[type="submit"],
.elementor-button-secondary input[type="button"],
.elementor-button-secondary input[type="submit"],
.elementor-element .elementor-button-secondary .elementor-button,
.button-outline-secondary:hover,
.elementor-wpcf7-button-outline_secondary input:hover[type="submit"],
.elementor-wpcf7-button-outline_secondary button:hover[type="submit"],
.mailchimp-button-outline_secondary button:hover,
.button-outline-secondary:active,
.elementor-wpcf7-button-outline_secondary input:active[type="submit"],
.elementor-wpcf7-button-outline_secondary button:active[type="submit"],
.mailchimp-button-outline_secondary button:active,
.button-outline-secondary.active,
.elementor-wpcf7-button-outline_secondary input.active[type="submit"],
.elementor-wpcf7-button-outline_secondary button.active[type="submit"],
.mailchimp-button-outline_secondary button.active,
.show > .button-outline-secondary.dropdown-toggle,
.elementor-wpcf7-button-outline_secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-outline_secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-outline_secondary .show > button.dropdown-toggle,
.elementor-element .elementor-button-outline_secondary .elementor-button:hover,
.elementor-element .elementor-button-outline_secondary .elementor-button:active,
.elementor-element .elementor-button-outline_secondary .elementor-button:focus,
.bg-secondary,
#secondary .elementor-widget-wp-widget-categories a:before,
.elementor-widget-sidebar .elementor-widget-wp-widget-categories a:before,
#give-sidebar-left .elementor-widget-wp-widget-categories a:before,
.elementor-flip-box__back,
.opal-image-hotspots-main-icons .opal-image-hotspots-icon.style-2,
.elementor-widget-opal-text_carousel.text-carousel-style-2 .owl-theme.owl-carousel .owl-nav [class*='owl-']:before,
.elementor-widget-opal-timeline .elementor-content-wrap,
form[id*='give-form'] .give-donation-amount .give-currency-symbol,
.give-btn.give-default-level,
.give-btn:focus,
.give-btn:hover {
  background-color: {$color_secondary->toCss()}; }


.page-links a:hover,
.page-links .post-page-numbers.current,
.button-secondary,
.secondary-button .search-submit,
.elementor-wpcf7-button-secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-secondary input[type="submit"],
.elementor-wpcf7-button-secondary button[type="submit"],
.mailchimp-button-secondary button,
.mailchimp-button-secondary button[type="submit"],
.elementor-button-secondary button[type="submit"],
.elementor-button-secondary input[type="button"],
.elementor-button-secondary input[type="submit"],
.elementor-element .elementor-button-secondary .elementor-button,
.button-outline-secondary,
.elementor-wpcf7-button-outline_secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-outline_secondary input[type="submit"],
.elementor-wpcf7-button-outline_secondary button[type="submit"],
.mailchimp-button-outline_secondary button,
.mailchimp-button-outline_secondary button[type="submit"],
.elementor-element .elementor-button-outline_secondary .elementor-button,
.button-outline-secondary:hover,
.elementor-wpcf7-button-outline_secondary input:hover[type="submit"],
.elementor-wpcf7-button-outline_secondary button:hover[type="submit"],
.button-outline-secondary:active,
.elementor-wpcf7-button-outline_secondary input:active[type="submit"],
.elementor-wpcf7-button-outline_secondary button:active[type="submit"],
.button-outline-secondary.active,
.elementor-wpcf7-button-outline_secondary input.active[type="submit"],
.elementor-wpcf7-button-outline_secondary button.active[type="submit"],
.show > .button-outline-secondary.dropdown-toggle,
.elementor-wpcf7-button-outline_secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-outline_secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-outline_secondary .show > button.dropdown-toggle,
.elementor-element .elementor-button-outline_secondary .elementor-button:hover,
.elementor-element .elementor-button-outline_secondary .elementor-button:active,
.elementor-element .elementor-button-outline_secondary .elementor-button:focus,
.b-secondary,
.give-btn.give-default-level,
.give-btn:focus,
.give-btn:hover {
  border-color: {$color_secondary->toCss()}; }



.button-secondary:hover,
.secondary-button .search-submit:hover,
.elementor-wpcf7-button-secondary input:hover[type="submit"],
.elementor-wpcf7-button-secondary button:hover[type="submit"],
.mailchimp-button-secondary button:hover,
.button-secondary:active,
.secondary-button .search-submit:active,
.elementor-wpcf7-button-secondary input:active[type="submit"],
.elementor-wpcf7-button-secondary button:active[type="submit"],
.mailchimp-button-secondary button:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.elementor-wpcf7-button-secondary input.active[type="submit"],
.elementor-wpcf7-button-secondary button.active[type="submit"],
.mailchimp-button-secondary button.active,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit,
.elementor-wpcf7-button-secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-secondary .show > button.dropdown-toggle,
.elementor-button-secondary button[type="submit"]:hover,
.elementor-button-secondary button[type="submit"]:active,
.elementor-button-secondary button[type="submit"]:focus,
.elementor-button-secondary input[type="button"]:hover,
.elementor-button-secondary input[type="button"]:active,
.elementor-button-secondary input[type="button"]:focus,
.elementor-button-secondary input[type="submit"]:hover,
.elementor-button-secondary input[type="submit"]:active,
.elementor-button-secondary input[type="submit"]:focus,
.elementor-element .elementor-button-secondary .elementor-button:hover,
.elementor-element .elementor-button-secondary .elementor-button:active,
.elementor-element .elementor-button-secondary .elementor-button:focus {
  background-color: {$color_secondary_hover->toCss()}; }


.button-secondary:hover,
.secondary-button .search-submit:hover,
.elementor-wpcf7-button-secondary input:hover[type="submit"],
.elementor-wpcf7-button-secondary button:hover[type="submit"],
.mailchimp-button-secondary button:hover,
.button-secondary:active,
.secondary-button .search-submit:active,
.elementor-wpcf7-button-secondary input:active[type="submit"],
.elementor-wpcf7-button-secondary button:active[type="submit"],
.mailchimp-button-secondary button:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.elementor-wpcf7-button-secondary input.active[type="submit"],
.elementor-wpcf7-button-secondary button.active[type="submit"],
.mailchimp-button-secondary button.active,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit,
.elementor-wpcf7-button-secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-secondary .show > button.dropdown-toggle,
.elementor-button-secondary button[type="submit"]:hover,
.elementor-button-secondary button[type="submit"]:active,
.elementor-button-secondary button[type="submit"]:focus,
.elementor-button-secondary input[type="button"]:hover,
.elementor-button-secondary input[type="button"]:active,
.elementor-button-secondary input[type="button"]:focus,
.elementor-button-secondary input[type="submit"]:hover,
.elementor-button-secondary input[type="submit"]:active,
.elementor-button-secondary input[type="submit"]:focus,
.elementor-element .elementor-button-secondary .elementor-button:hover,
.elementor-element .elementor-button-secondary .elementor-button:active,
.elementor-element .elementor-button-secondary .elementor-button:focus {
  border-color: {$color_secondary_hover->toCss()}; }


CSS;
    return $cssCode;
}
add_filter('osf_customize_grid', 'osf_typography_grid_bootstrap', 10 , 2);
function osf_typography_grid_bootstrap($cssCode, $gridGutter){
    $cssCode .= <<<CSS

.row,
body.opal-content-layout-2cl #content .wrap,
body.opal-content-layout-2cr #content .wrap,
[data-opal-columns],
.opal-default-content-layout-2cr .site-content .wrap,
.site-footer .widget-area,
.comment-form,
.widget .gallery,
.elementor-element .gallery,
.entry-gallery .gallery,
.single .gallery,
.blog .gallery,
[data-elementor-columns],
.feature-campaign__item .campaign-item-wrap,
.elementor-widget-opal-schedules .schedules-style-2 .elementor-schedules-item,
.give-wrap-inner > .give_forms {
    margin-right: -{$gridGutter}px;
    margin-left: -{$gridGutter}px;
}



.col-1,
.col-2,
[data-elementor-columns-mobile="6"] .column-item,
.col-3,
[data-elementor-columns-mobile="4"] .column-item,
.col-4,
.comment-form .comment-form-author,
.comment-form .comment-form-email,
.comment-form .comment-form-url,
[data-elementor-columns-mobile="3"] .column-item,
.col-5,
.col-6,
[data-elementor-columns-mobile="2"] .column-item,
.col-7,
.col-8,
.col-9,
.col-10,
.col-11,
.col-12,
.opal-archive-style-2.opal-content-layout-2cr .post-style-2,
.related-posts .column-item,
.opal-default-content-layout-2cr .related-posts .column-item,
.opal-content-layout-2cr .related-posts .column-item,
.opal-content-layout-2cl .related-posts .column-item,
.site-footer .widget-area .widget-column,
.comment-form .logged-in-as,
.comment-form .comment-notes,
.comment-form .comment-form-comment,
.comment-form .form-submit,
.widget .gallery-columns-1 .gallery-item,
.elementor-element .gallery-columns-1 .gallery-item,
.entry-gallery .gallery-columns-1 .gallery-item,
.single .gallery-columns-1 .gallery-item,
.blog .gallery-columns-1 .gallery-item,
[data-elementor-columns-mobile="1"] .column-item,
.give-wrap-inner .entry-summary,
.col,
body #secondary,
body .elementor-widget-sidebar,
body #give-sidebar-left,
.elementor-widget-opal-schedules .schedules-style-2 .elementor-schedules-inner-day,
.elementor-widget-opal-schedules .schedules-style-2 .elementor-schedules-inner-item,
.col-auto,
.col-sm-1,
[data-opal-columns="12"] .column-item,
.col-sm-2,
[data-opal-columns="6"] .column-item,
.col-sm-3,
[data-opal-columns="4"] .column-item,
.col-sm-4,
[data-opal-columns="3"] .column-item,
.widget .gallery-columns-6 .gallery-item,
.elementor-element .gallery-columns-6 .gallery-item,
.entry-gallery .gallery-columns-6 .gallery-item,
.single .gallery-columns-6 .gallery-item,
.blog .gallery-columns-6 .gallery-item,
.col-sm-5,
.col-sm-6,
[data-opal-columns="2"] .column-item,
.opal-archive-style-3:not(.opal-content-layout-2cr) .post-style-3,
.widget .gallery-columns-2 .gallery-item,
.elementor-element .gallery-columns-2 .gallery-item,
.entry-gallery .gallery-columns-2 .gallery-item,
.single .gallery-columns-2 .gallery-item,
.blog .gallery-columns-2 .gallery-item,
.widget .gallery-columns-3 .gallery-item,
.elementor-element .gallery-columns-3 .gallery-item,
.entry-gallery .gallery-columns-3 .gallery-item,
.single .gallery-columns-3 .gallery-item,
.blog .gallery-columns-3 .gallery-item,
.widget .gallery-columns-4 .gallery-item,
.elementor-element .gallery-columns-4 .gallery-item,
.entry-gallery .gallery-columns-4 .gallery-item,
.single .gallery-columns-4 .gallery-item,
.blog .gallery-columns-4 .gallery-item,
.col-sm-7,
.col-sm-8,
.col-sm-9,
.col-sm-10,
.col-sm-11,
.col-sm-12,
[data-opal-columns="1"] .column-item,
.opal-archive-style-2:not(.opal-content-layout-2cr) .post-style-2,
.opal-archive-style-3.opal-content-layout-2cr .post-style-3,
.col-sm,
.col-sm-auto,
.col-md-1,
.col-md-2,
[data-elementor-columns-tablet="6"] .column-item,
.col-md-3,
[data-elementor-columns-tablet="4"] .column-item,
.col-md-4,
[data-elementor-columns-tablet="3"] .column-item,
.col-md-5,
.opal-default-content-layout-2cr #secondary,
.opal-default-content-layout-2cr .elementor-widget-sidebar,
.opal-default-content-layout-2cr #give-sidebar-left,
.col-md-6,
[data-elementor-columns-tablet="2"] .column-item,
.col-md-7,
.opal-default-content-layout-2cr #primary,
.col-md-8,
.col-md-9,
.col-md-10,
#give_profile_editor_form fieldset,
.col-md-11,
.col-md-12,
[data-elementor-columns-tablet="1"] .column-item,
.elementor-campaign-feature-wrapper .campaign-body,
.elementor-campaign-feature-wrapper .campaign-media,
.elementor-widget-opal-image-hotspots .opal-image-hotspots-accordion,
.elementor-widget-opal-image-hotspots .opal-image-hotspots-accordion + .opal-image-hotspots-container,
.col-md,
.col-md-auto,
.col-lg-1,
.col-lg-2,
[data-elementor-columns="6"] .column-item,
.col-lg-3,
[data-elementor-columns="4"] .column-item,
.col-lg-4,
[data-elementor-columns="3"] .column-item,
.col-lg-5,
.col-lg-6,
[data-elementor-columns="2"] .column-item,
.col-lg-7,
.col-lg-8,
.col-lg-9,
.col-lg-10,
.col-lg-11,
.col-lg-12,
[data-elementor-columns="1"] .column-item,
.col-lg,
.col-lg-auto,
.col-xl-1,
.col-xl-2,
.col-xl-3,
.col-xl-4,
.col-xl-5,
.col-xl-6,
.col-xl-7,
.col-xl-8,
.col-xl-9,
.col-xl-10,
.col-xl-11,
.col-xl-12,
.col-xl,
.col-xl-auto {
    padding-right: {$gridGutter}px;
    padding-left: {$gridGutter}px;
}



.container,
#content,
ul.elementor-nav-menu--dropdown.mega-containerwidth > li.mega-menu-item > .elementor {
    padding-right: {$gridGutter}px;
    padding-left: {$gridGutter}px;
}
  @media (min-width: 576px) {
    .container, #content, ul.elementor-nav-menu--dropdown.mega-containerwidth > li.mega-menu-item > .elementor {
      max-width: 540px; } }
  @media (min-width: 768px) {
    .container, #content, ul.elementor-nav-menu--dropdown.mega-containerwidth > li.mega-menu-item > .elementor {
      max-width: 720px; } }
  @media (min-width: 992px) {
    .container, #content, ul.elementor-nav-menu--dropdown.mega-containerwidth > li.mega-menu-item > .elementor {
      max-width: 960px; } }
  @media (min-width: 1200px) {
    .container, #content, ul.elementor-nav-menu--dropdown.mega-containerwidth > li.mega-menu-item > .elementor {
      max-width: 1140px; } }


CSS;
    return $cssCode;
}
add_filter('osf_customize_button_primary_color', 'osf_typography_button_primary_color', 10 , 11);
function osf_typography_button_primary_color($cssCode, $primary, $primary_hover, $primary_border, $primary_border_hover, $primary_color, $primary_color_hover, $primary_color_outline, $button_css, $font_style_code){
    $cssCode .= <<<CSS


.button-primary,
.scrollup,
.elementor-widget-opal-account .site-header-account .account-dropdown .account-inner button[type="submit"],
.contactform-content input[type="button"],
.contactform-content input[type="submit"],
.contactform-content button[type="submit"],
.elementor-wpcf7-button-primary_gradient input[type="button"][type="submit"],
.elementor-wpcf7-button-primary_gradient input[type="submit"],
.elementor-wpcf7-button-primary_gradient button[type="submit"],
.elementor-wpcf7-button-primary input[type="button"][type="submit"],
.elementor-wpcf7-button-primary input[type="submit"],
.elementor-wpcf7-button-primary button[type="submit"],
.elementor-widget-opal-give-form .give-submit-button-wrap .give-submit,
.mailchimp-button-primary button,
.mailchimp-button-primary button[type="submit"],
[id^='give-user-login-submit'] .give-submit,
.give-submit-button-wrap .give-submit,
button.give-btn-reveal,
button.give-btn-modal,
.give-wrap .btn-donate-now,
.button-dark:hover,
.elementor-element .elementor-button-dark .elementor-button:hover,
.mailchimp-button-dark button:hover,
.button-dark:active,
.elementor-element .elementor-button-dark .elementor-button:active,
.mailchimp-button-dark button:active,
.button-dark:focus,
.elementor-element .elementor-button-dark .elementor-button:focus,
.mailchimp-button-dark button:focus,
.button-light:hover,
.elementor-element .elementor-button-light .elementor-button:hover,
.mailchimp-button-light button:hover,
.button-light:active,
.elementor-element .elementor-button-light .elementor-button:active,
.mailchimp-button-light button:active,
.button-light:focus,
.elementor-element .elementor-button-light .elementor-button:focus,
.mailchimp-button-light button:focus,
.wp-block-button__link:hover,
.elementor-element .elementor-button-primary .elementor-button {
    background-color: {$primary};
    border-color: {$primary};
    color: {$primary_color};
    {$button_css}
    {$font_style_code}
}



.button-primary:hover,
.scrollup:hover,
.elementor-widget-opal-account .site-header-account .account-dropdown .account-inner button:hover[type="submit"],
.contactform-content input:hover[type="button"],
.contactform-content input:hover[type="submit"],
.contactform-content button:hover[type="submit"],
.elementor-wpcf7-button-primary_gradient input:hover[type="submit"],
.elementor-wpcf7-button-primary_gradient button:hover[type="submit"],
.elementor-wpcf7-button-primary input:hover[type="submit"],
.elementor-wpcf7-button-primary button:hover[type="submit"],
.mailchimp-button-primary button:hover,
[id^='give-user-login-submit'] .give-submit:hover,
.give-submit-button-wrap .give-submit:hover,
button.give-btn-reveal:hover,
button.give-btn-modal:hover,
.give-wrap .btn-donate-now:hover,
.button-primary:active,
.scrollup:active,
.elementor-widget-opal-account .site-header-account .account-dropdown .account-inner button:active[type="submit"],
.contactform-content input:active[type="button"],
.contactform-content input:active[type="submit"],
.contactform-content button:active[type="submit"],
.elementor-wpcf7-button-primary_gradient input:active[type="submit"],
.elementor-wpcf7-button-primary_gradient button:active[type="submit"],
.elementor-wpcf7-button-primary input:active[type="submit"],
.elementor-wpcf7-button-primary button:active[type="submit"],
.mailchimp-button-primary button:active,
[id^='give-user-login-submit'] .give-submit:active,
.give-submit-button-wrap .give-submit:active,
button.give-btn-reveal:active,
button.give-btn-modal:active,
.give-wrap .btn-donate-now:active,
.button-primary.active,
.active.scrollup,
.elementor-widget-opal-account .site-header-account .account-dropdown .account-inner button.active[type="submit"],
.contactform-content input.active[type="button"],
.contactform-content input.active[type="submit"],
.contactform-content button.active[type="submit"],
.elementor-wpcf7-button-primary_gradient input.active[type="submit"],
.elementor-wpcf7-button-primary_gradient button.active[type="submit"],
.elementor-wpcf7-button-primary input.active[type="submit"],
.elementor-wpcf7-button-primary button.active[type="submit"],
.mailchimp-button-primary button.active,
[id^='give-user-login-submit'] .active.give-submit,
.give-submit-button-wrap .active.give-submit,
button.active.give-btn-reveal,
button.active.give-btn-modal,
.give-wrap .active.btn-donate-now,
.show > .button-primary.dropdown-toggle,
.show > .dropdown-toggle.scrollup,
.elementor-widget-opal-account .site-header-account .account-dropdown .account-inner .show > button.dropdown-toggle[type="submit"],
.contactform-content .show > input.dropdown-toggle[type="button"],
.contactform-content .show > input.dropdown-toggle[type="submit"],
.contactform-content .show > button.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary_gradient .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary_gradient .show > button.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-primary .show > button.dropdown-toggle,
[id^='give-user-login-submit'] .show > .dropdown-toggle.give-submit,
.give-submit-button-wrap .show > .dropdown-toggle.give-submit,
.show > button.dropdown-toggle.give-btn-reveal,
.show > button.dropdown-toggle.give-btn-modal,
.give-wrap .show > .dropdown-toggle.btn-donate-now,
.elementor-element .elementor-button-primary .elementor-button:hover,
.elementor-element .elementor-button-primary .elementor-button:active,
.elementor-element .elementor-button-primary .elementor-button:focus {
    background-color: {$primary_hover};
    border-color: {$primary_hover};
    color: {$primary_color_hover};
    {$button_css}
    {$font_style_code}
}


CSS;
    return $cssCode;
}

add_filter('osf_customize_button_secondary_color', 'osf_typography_button_secondary_color', 10 , 11);
function osf_typography_button_secondary_color($cssCode, $secondary, $secondary_hover, $secondary_border, $secondary_border_hover, $secondary_color, $secondary_color_hover, $secondary_color_outline, $button_css, $font_style_code){
    $cssCode .= <<<CSS


.button-secondary,
.secondary-button .search-submit,
.elementor-wpcf7-button-secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-secondary input[type="submit"],
.elementor-wpcf7-button-secondary button[type="submit"],
.mailchimp-button-secondary button,
.mailchimp-button-secondary button[type="submit"],
.elementor-button-secondary button[type="submit"],
.elementor-button-secondary input[type="button"],
.elementor-button-secondary input[type="submit"],
.elementor-element .elementor-button-secondary .elementor-button {
    background-color: {$secondary};
    border-color: {$secondary};
    color: {$secondary_color};
    {$button_css}
    {$font_style_code}
}



.button-secondary:hover,
.secondary-button .search-submit:hover,
.elementor-wpcf7-button-secondary input:hover[type="submit"],
.elementor-wpcf7-button-secondary button:hover[type="submit"],
.mailchimp-button-secondary button:hover,
.button-secondary:active,
.secondary-button .search-submit:active,
.elementor-wpcf7-button-secondary input:active[type="submit"],
.elementor-wpcf7-button-secondary button:active[type="submit"],
.mailchimp-button-secondary button:active,
.button-secondary.active,
.secondary-button .active.search-submit,
.elementor-wpcf7-button-secondary input.active[type="submit"],
.elementor-wpcf7-button-secondary button.active[type="submit"],
.mailchimp-button-secondary button.active,
.show > .button-secondary.dropdown-toggle,
.secondary-button .show > .dropdown-toggle.search-submit,
.elementor-wpcf7-button-secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-secondary .show > button.dropdown-toggle,
.elementor-button-secondary button[type="submit"]:hover,
.elementor-button-secondary button[type="submit"]:active,
.elementor-button-secondary button[type="submit"]:focus,
.elementor-button-secondary input[type="button"]:hover,
.elementor-button-secondary input[type="button"]:active,
.elementor-button-secondary input[type="button"]:focus,
.elementor-button-secondary input[type="submit"]:hover,
.elementor-button-secondary input[type="submit"]:active,
.elementor-button-secondary input[type="submit"]:focus,
.elementor-element .elementor-button-secondary .elementor-button:hover,
.elementor-element .elementor-button-secondary .elementor-button:active,
.elementor-element .elementor-button-secondary .elementor-button:focus {
    background-color: {$secondary_hover};
    border-color: {$secondary_hover};
    color: {$secondary_color};
    {$button_css}
    {$font_style_code}
}


CSS;
    return $cssCode;
}
add_filter('osf_customize_typo_heading', 'osf_typography_custom_typo_heading', 10 , 2);
function osf_typography_custom_typo_heading($cssCode, $heading_css){
    $cssCode .= <<<CSS

.typo-heading,
h1,
h2,
h3,
h4,
h5,
h6,
.site-title,
.author-wrapper .author-name,
.error404 h1,
.error404 .error-404-subtitle,
.error404 .error-btn-bh,
h2.widget-title,
h2.widgettitle,
.profile-wrapper .login-form-title,
.widget_recent_entries li.item-recent-post a,
#secondary .elementor-widget-container h5:first-of-type,
.elementor-widget-sidebar .elementor-widget-container h5:first-of-type,
#give-sidebar-left .elementor-widget-container h5:first-of-type,
.elementor-widget-opal-account .site-header-account .account-dashboard li a,
.contactform-content .form-title,
.elementor-widget-opal-countdown .elementor-countdown-digits,
.elementor-widget-opal-countdown .elementor-countdown-label,
.elementor-widget-opal-featured-box .elementor-featured-box-name,
.elementor-give-category-title,
.elementor-campaign-feature-wrapper .owl-theme.owl-carousel .owl-dots .owl-dot,
.elementor-widget-opal-give-form .give-display-modal form[id*='give-form'] .give-donation-amount #give-amount,
.elementor-widget-opal-give-form .give-display-modal form[id*='give-form'] .give-donation-amount #give-text-input,
.elementor-widget-opal-give-form .give-display-modal form[id*='give-form'] .give-donation-amount #give-amount-text,
.elementor-widget-opal-give-form .give-donation-level-btn,
.elementor-widget-opal-give-form .give-display-onpage form[id*='give-form'] .give-donation-amount #give-amount,
.elementor-widget-opal-give-form .give-display-onpage form[id*='give-form'] .give-donation-amount #give-text-input,
.elementor-widget-opal-give-form .give-display-onpage form[id*='give-form'] .give-donation-amount #give-amount-text,
.elementor-widget-heading .elementor-heading-title,
.tooltipster-sidetip div.opal-image-hotspots-tooltips-text,
.elementor-widget-opal-phone .elementor-phone-title,
.elementor-widget-opal-phone .elementor-phone-subtitle,
.elementor-price-table__price span,
.elementor-price-table__period,
.elementor-widget-opal-schedules .schedules-day-name,
.elementor-widget-opal-schedules .schedules-day-time,
.elementor-widget-opal-schedules .title-schedules,
.elementor-teams-wrapper .elementor-team-name,
.elementor-teams-wrapper .elementor-team-job,
.elementor-widget-opal-testimonials .elementor-testimonial-title,
.elementor-widget-opal-testimonials .elementor-testimonial-name,
.elementor-widget-opal-timeline .timeline-pagination li,
.elementor-video-title,
form[id*='give-form'] h3.give-section-break,
form[id*='give-form'] h4.give-section-break,
form[id*='give-form'] legend,
#give-recurring-form h3.give-section-break,
#give-recurring-form h4.give-section-break,
#give-recurring-form legend,
form.give-form h3.give-section-break,
form.give-form h4.give-section-break,
form.give-form legend,
form[id*='give-form'] #give-final-total-wrap .give-donation-total-label,
form[id*='give-form'] #give-final-total-wrap .give-final-total-amount,
#give_profile_editor_form legend,
.give-donor__image,
.give-goal-progress .goal,
.give-goal-progress .income,
.give-goal-progress .donors,
.give-goal-progress .time-left,
.give-goal-progress .percentage,
.give-wrap .give-card__category,
.give-wrap div [class*='media'] .label,
.give-wrap .give-form-tabs .ui-tabs-nav li,
.give-wrap .barometer span span,
.give-wrap .sidebar-creator .author-name,
.give-wrap .sidebar-creator .campaigns-count,
.single-osf_story .post-navigation .nav-links .nav-links-inner .nav-title,
.single-osf_story .post-navigation .nav-links .nav-links-inner .meta-nav {
    {$heading_css}
}


CSS;
    return $cssCode;
}

add_filter('osf_customize_typo_tertiary', 'osf_typography_custom_typo_tertiary', 10 , 2);
function osf_typography_custom_typo_tertiary($cssCode, $tertiary_css){
    $cssCode .= <<<CSS

.typo-tertiary,
.button-default,
.sidebar-donor-wall .give-donor__load_more,
.button-primary,
.scrollup,
.elementor-widget-opal-account .site-header-account .account-dropdown .account-inner button[type="submit"],
.contactform-content input[type="button"],
.contactform-content input[type="submit"],
.contactform-content button[type="submit"],
.elementor-wpcf7-button-primary_gradient input[type="button"][type="submit"],
.elementor-wpcf7-button-primary_gradient input[type="submit"],
.elementor-wpcf7-button-primary_gradient button[type="submit"],
.elementor-wpcf7-button-primary input[type="button"][type="submit"],
.elementor-wpcf7-button-primary input[type="submit"],
.elementor-wpcf7-button-primary button[type="submit"],
.elementor-widget-opal-give-form .give-submit-button-wrap .give-submit,
.mailchimp-button-primary button,
.mailchimp-button-primary button[type="submit"],
[id^='give-user-login-submit'] .give-submit,
.give-submit-button-wrap .give-submit,
button.give-btn-reveal,
button.give-btn-modal,
.give-wrap .btn-donate-now,
.button-secondary,
.secondary-button .search-submit,
.elementor-wpcf7-button-secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-secondary input[type="submit"],
.elementor-wpcf7-button-secondary button[type="submit"],
.mailchimp-button-secondary button,
.mailchimp-button-secondary button[type="submit"],
.button-outline-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.post-inner .more-link,
.more-link,
.comment-form .form-submit input[type="submit"],
.elementor-wpcf7-button-outline_primary input[type="button"],
.elementor-wpcf7-button-outline_primary input[type="submit"],
.elementor-wpcf7-button-outline_primary button[type="submit"],
.mailchimp-button-outline_primary button,
.mailchimp-button-outline_primary button[type="submit"],
.button-outline-secondary,
.elementor-wpcf7-button-outline_secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-outline_secondary input[type="submit"],
.elementor-wpcf7-button-outline_secondary button[type="submit"],
.mailchimp-button-outline_secondary button,
.mailchimp-button-outline_secondary button[type="submit"],
.btn-link,
.elementor-element .elementor-button-link .elementor-button,
.button-link,
.mailchimp-button-link button,
.mailchimp-button-link button[type="submit"],
.button-dark,
.elementor-element .elementor-button-dark .elementor-button,
.mailchimp-button-dark button,
.mailchimp-button-dark button[type="submit"],
.button-light,
.elementor-element .elementor-button-light .elementor-button,
.mailchimp-button-light button,
.mailchimp-button-light button[type="submit"],
.widget_recent_entries .post-date {
    {$tertiary_css}
}


CSS;
    return $cssCode;
}
 
add_filter('osf_customize_typo_quaternary', 'osf_typography_custom_typo_quaternary', 10 , 2);
function osf_typography_custom_typo_quaternary($cssCode, $quaternary_css){
    $cssCode .= <<<CSS
CSS;
    return $cssCode;
}
